### ISSUE TITLE
When Injecting EF6 IService in Quartz.Unity jobs, it doesn't run.

### ISSUE THREAD

**Issue by get2sunil** [hbiarge/Quartz.Unity#10]
Hello,

When Injecting EF6 IService in Quartz.Unity jobs, it doesn't run.

Sample:     
public interface IUserProfileService : IService<UserProfile>{
}

public class SendQueueEmailJob : IJob
    {
        private readonly IUserProfileService _userProfileService;
 SendQueueEmailJob(IUserProfileService userProfileService)
        {
            _userProfileService = userProfileService;
        }
}

Without Injection, jobs runs as it should.

Sunil

**Comment by hbiarge** [comment]
Hi Sunil!

Is the IUserProfileService registered in the container with a valid implementation, rigth?

**Comment by get2sunil** [comment]
Hello 
Yes Its works fine in api controller.

 public RegisterController(IUserProfileService userProfileService)
        {
            _userProfileService = userProfileService;
        }

**Comment by hbiarge** [comment]
Check the example implementation here: https://github.com/hbiarge/Quartz.Unity/blob/master/Quartz.Net/Example/Program.cs

Verify that you are registering the factories module (line 21) in Unity and how are you scheduling the jobs (line 27).

Other than that I don't know what can be happening. I don't know the framework you mention.

**Comment by get2sunil** [comment]
Hello Expert,

Here is my revised code:

ICountryService  is injected and works fine in controller.

public class HomeController : Controller
    {
        private readonly ICountryService _countryService;
        public HomeController(ICountryService countryService)
        {
            _countryService = countryService;
        }
        public ActionResult Index()
        {
            var data = _countryService.Queryable().Where(x => x.NumericIsoCode != 1).ToList();
            if (data.Any())
            {
                ViewBag.Title = "Home Page Count: " + data.Count();
            }
            else
            {
                ViewBag.Title = "Home Page";
            }
            return View();
        }

    }

Here is country job is works fine without ICountryService countryService. When I Inject ICountryService  job doesn't work.

 public class CountryListJob : IJob
   {

       private readonly ICountryService _countryService;
       public CountryListJob(ICountryService countryService)
       {
           _countryService = countryService;

       }
        public void Execute(IJobExecutionContext context)
        {
            Console.WriteLine("aaaa");
        }

    }

Here is my full source project with quartz unity.
https://drive.google.com/file/d/0B9rL4JNdRAl3eXFSTktDdUxncDA/view


 I will appreciate any help. Thank you 

Sunil

**Comment by hbiarge** [comment]
As I mentioned you need to register the QuartUnityExtension in your Unity container.

Add this line to your UnityConfig.cs:
container.AddNewExtension<QuartzUnityExtension>();

**Comment by get2sunil** [comment]
Have tried using that also.Still same problem.
