### ISSUE TITLE
Support Quartz 3.0-*

### ISSUE THREAD

**Issue by FSou1** [hbiarge/Quartz.Unity#12]
Looks like coming major update of quartz at version 3.0-\* (for example, migrating from sync to async/await executing of jobs).

Have you got a plan to update your package?

**Comment by hbiarge** [comment]
Sure!
As soon they ship v3, this package will be updated.

**Comment by hbiarge** [comment]
Working on this...

**Comment by hbiarge** [comment]
Resolved. See #15
