### ISSUE TITLE
App.config and add extension

### ISSUE THREAD

**Issue by michal-gajda** [hbiarge/Quartz.Unity#13]
<extensions>
        <add type="Quartz.Unity.QuartzUnityExtension, Quartz.Unity.45" />
      </extensions>

Why this not working?

**Comment by hbiarge** [comment]
Please, context.
Which file is this and in which section? Why dou you think it should work?

**Comment by mr-owl** [comment]
Hi,

I am trying move all Quartz configuration to App.config and xml file. I have got problem to add this extension by configuration file. When I am adding
  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
    <container>
     <extensions>
        <add type="Quartz.Unity.QuartzUnityExtension, Quartz.Unity.45" />
      </extensions>
    </container>
</unity>
The job object is not created but when I am adding this.Container.AddNewExtension<QuartzUnityExtension>(); in my Bootstrapper class everything is working just fine.
Why can not I use the configuration file to add this extension?

Kind regards,

michal

**Comment by hbiarge** [comment]
The Unity documentation for registering [extensions in Xml configuration](https://msdn.microsoft.com/en-us/library/ff660914(v=pandp.20).aspx?cs-save-lang=1&cs-lang=csharp#Anchor_11) says this is the correct syntax is:
```
<container>
    <extension type="Microsoft.Practices.Unity.Interception.InterceptionExtension, Microsoft.Practices.Unity.Interception" />
</container>
```

Have you tried it?
