### ISSUE TITLE
Quartz 3.0.0 - not working

### ISSUE THREAD

**Issue by Masherak** [hbiarge/Quartz.Unity#15]
Will be v.3 supported?

`Exception occurred while: while resolving.
Exception is: MissingMethodException - Method not found: 'Quartz.IScheduler Quartz.ISchedulerFactory.GetScheduler()'.`
  
Thank you for your time!

**Comment by hbiarge** [comment]
I started working on this. Hope I can finish the update this weekend...

**Comment by hbiarge** [comment]
Published version 3.0.0 with support to Quartz 3.0.0.
Be aware that there are breaking changes, because the `ISchedulerFactory `API is async now.
I've removed the `IScheduler `registration, so you need to inject a `ISchedulerFactory `now and create the `IScheduler ` from it.

**Comment by Masherak** [comment]
Everything works as expected, thank you very much!
