### ISSUE TITLE
The NuGet package stopped working since Common.Logging 3.0

### ISSUE THREAD

**Issue by AxlPr** [hbiarge/Quartz.Unity#6]
Since upgrading my Nuget packages (.Net 4.5) I'm now seeing an error:

"The type initializer for 'Quartz.Unity.UnityJobFactory' threw an exception."
"Method not found: 'Common.Logging.ILog Common.Logging.LogManager.GetLogger(System.Type)'."

Package versions are:

Quartz.Net = 2.3.1
Common.Logging = 3.0.0
Unity=3.5.1404.0

It looks like Common.Logging has made a breaking change by moving the Common.Logging.ILog interface into the Common.Logging.Core assembly. Would it be possible to recompile this project and republish to resolve this issue? For now we need to stay on the previous version of the packages.

Thanks.

**Comment by hbiarge** [comment]
Investigating...
I'll update the nugets ASAP...

**Comment by hbiarge** [comment]
Done!
Package updated with dependencies updated to Quartz v2.3.1.
This version of Quartz depends on Common.Loggin v3.0.0, so your issue should be solved.

Thank you!

**Comment by AxlPr** [comment]
Hi. Just pulled in the latest packages and its working great.

Thanks for all the great work on this.
