### ISSUE TITLE
typo in .NET 4.0 nuget dependencies

### ISSUE THREAD

**Issue by hulkkii** [hbiarge/Quartz.Unity#7]
When trying to install Quartz.Unity 1.3.0 from nuget in .net 4.0 project:
Unable to resolve dependency 'Quart (≥ 2.3.1)'.
So 'z' missing from Quartz.

**Comment by hbiarge** [comment]
Oops!
I'll fix this ASAP

-----Mensaje original-----
De: "hulkkii" <notifications@github.com>
Enviado: ‎29/‎01/‎2015 12:12
Para: "hbiarge/Quartz.Unity" <Quartz.Unity@noreply.github.com>
Asunto: [Quartz.Unity] typo in .NET 4.0 nuget dependencies (#7)

When trying to install Quartz.Unity 1.3.0 from nuget in .net 4.0 project:
Unable to resolve dependency 'Quart (≥ 2.3.1)'.
So 'z' missing from Quartz.

**Comment by hbiarge** [comment]
Done!
It should be fixed now.
